import Image from "next/image";
import HomePage from "./pages/Index";
import EditPage from "./components/EditPage";
import type { Metadata } from "next";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <HomePage />
    </div>
  );
}
